version: '3.8'

services:
  video-combine:
    build: 
      context: .
      target: development
    ports:
      - "8005:8005"
    volumes:
      - .:/app  # Mount entire project directory for live updates
      - ./tmp:/app/tmp  # Persistent tmp directory
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    command: uvicorn main:app --host 0.0.0.0 --port 8005 --reload  # Enable hot reload
    restart: unless-stopped 