version: '3.8'

services:
  video-combine:
    build: 
      context: .
      target: production
    ports:
      - "8005:8005"
    volumes:
      - ./tmp:/app/tmp  # Persistent tmp directory
      - model-cache:/app/.cache  # Persistent model cache
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
      - WORKERS=4
      - HF_HOME=/app/.cache/huggingface
      - TRANSFORMERS_CACHE=/app/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Security options
    security_opt:
      - no-new-privileges:true
    # Network configuration
    networks:
      - video-combine-network

networks:
  video-combine-network:
    driver: bridge

volumes:
  model-cache:  # Persistent volume for Whisper models 